### PR TITLE
Fix device link functions not being called in a background thread

### PR DESCRIPTION
**Pull request by Mikunj**
I also went ahead and made a dedicated context for proof of work as to avoid the issue of it ever blocking the work contexts.

### CODE REVIEW

**Comment by nielsandriesse** [comment]
I wouldn't expect updating the device links to be performance intensive. It's just modifying a set, constructing a dictionary with a few values and then making an HTTP request. Any idea what exactly was blocking?

**Comment by Mikunj** [comment]
`setDeviceLinks` would be called upon the same main promise thread. Within that we have `retryIfNeeded` so if we ever got failures it would hold up one of the threads in the promise

**Comment by Mikunj** [comment]
I'm going to be going through and correcting all our promise code to work on correct threads where needed.

**Comment by Mikunj** [comment]
Closing this as we don't really need to do it.

**Pull request closed without merging**
